# Generated by Django 3.1.5 on 2021-08-15 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210815_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создание записи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blurred_consciousness',
            field=models.BooleanField(default=False, verbose_name='Помутнение сознания'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='chest_tightness',
            field=models.BooleanField(default=False, verbose_name='Чувство стеснения в груди'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='covid_grade',
            field=models.CharField(choices=[('1', 'low'), ('2', 'middle'), ('3', 'high')], max_length=1, verbose_name='Степень тяжести'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dizziness',
            field=models.BooleanField(default=False, verbose_name='Головокружения'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='headache',
            field=models.BooleanField(default=False, verbose_name='Головная боль'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_heart_rate',
            field=models.IntegerField(default=-1, verbose_name='Частота сердечных сокращений'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=40, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_saturation',
            field=models.IntegerField(default=-1, verbose_name='Сатурация'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_temperature',
            field=models.FloatField(default=0.0, verbose_name='Температура тела'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lung_damage',
            field=models.FloatField(default=0.0, verbose_name='Процент поражения лёгочной ткани'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(max_length=40, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='need_oxygen_support',
            field=models.BooleanField(default=False, verbose_name='Потребность в кислородной поддержке'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='shortness_of_breath',
            field=models.BooleanField(default=False, verbose_name='Наличие одышки'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sweating',
            field=models.BooleanField(default=False, verbose_name='Потливость'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='violation_of_balance_and_coordination',
            field=models.BooleanField(default=False, verbose_name='Нарушение равновесия и координации'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='vomiting',
            field=models.BooleanField(default=False, verbose_name='Рвота'),
        ),
    ]
