# Generated by Django 3.1.5 on 2021-08-15 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0013_auto_20210815_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='blurred_consciousness',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='chest_tightness',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='dizziness',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='headache',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_heart_rate',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_saturation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_temperature',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='need_oxygen_support',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='shortness_of_breath',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sweating',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='violation_of_balance_and_coordination',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='vomiting',
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создание пациента'),
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания записи')),
                ('last_temperature', models.FloatField(default=0.0, verbose_name='Температура тела')),
                ('last_heart_rate', models.IntegerField(default=-1, verbose_name='Частота сердечных сокращений')),
                ('last_saturation', models.IntegerField(default=-1, verbose_name='Сатурация')),
                ('shortness_of_breath', models.BooleanField(default=False, verbose_name='Наличие одышки')),
                ('chest_tightness', models.BooleanField(default=False, verbose_name='Чувство стеснения в груди')),
                ('vomiting', models.BooleanField(default=False, verbose_name='Рвота')),
                ('dizziness', models.BooleanField(default=False, verbose_name='Головокружения')),
                ('headache', models.BooleanField(default=False, verbose_name='Головная боль')),
                ('blurred_consciousness', models.BooleanField(default=False, verbose_name='Помутнение сознания')),
                ('sweating', models.BooleanField(default=False, verbose_name='Потливость')),
                ('violation_of_balance_and_coordination', models.BooleanField(default=False, verbose_name='Нарушение равновесия и координации')),
                ('need_oxygen_support', models.BooleanField(default=False, verbose_name='Потребность в кислородной поддержке')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.patient')),
            ],
        ),
    ]
