# Generated by Django 3.1.5 on 2021-08-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20210815_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='last_heart_rate',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='last_temperature',
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='heart_rate',
            field=models.TextField(default='-1', verbose_name='Частота сердечных сокращений каждую минуту'),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='temperature_list',
            field=models.TextField(default='-1', verbose_name='Температура тела каждую минуту'),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='last_saturation',
            field=models.TextField(default='-1', verbose_name='Сатурация каждую минуту'),
        ),
    ]
