# Generated by Django 3.1.5 on 2021-08-19 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20210819_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='reviewcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reviewcomment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='reviewcomment',
            name='review',
        ),
        migrations.RemoveField(
            model_name='sentiment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='sentiment',
            name='review',
        ),
        migrations.RemoveField(
            model_name='shopcart',
            name='author',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='ReviewComment',
        ),
        migrations.DeleteModel(
            name='Sentiment',
        ),
        migrations.DeleteModel(
            name='ShopCart',
        ),
    ]
