# Generated by Django 3.1.5 on 2021-08-19 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20210819_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birth',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата рождения'),
            preserve_default=False,
        ),
    ]
