# Generated by Django 3.1.5 on 2021-08-19 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=40, verbose_name='Отчество')),
                ('birth', models.DateTimeField(verbose_name='Дата рождения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создание пациента')),
                ('address', models.TextField(max_length=100, verbose_name='Адрес')),
                ('covid_grade', models.CharField(choices=[('1', 'low'), ('2', 'middle'), ('3', 'high')], max_length=1, verbose_name='Степень тяжести')),
                ('lung_damage', models.FloatField(default=0.0, verbose_name='Процент поражения лёгочной ткани')),
                ('doctor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания записи')),
                ('temperature_list', models.TextField(default='-1', verbose_name='Температура тела каждую минуту')),
                ('heart_rate', models.TextField(default='-1', verbose_name='Частота сердечных сокращений каждую минуту')),
                ('last_saturation', models.TextField(default='-1', verbose_name='Сатурация каждую минуту')),
                ('shortness_of_breath', models.BooleanField(default=False, verbose_name='Наличие одышки')),
                ('chest_tightness', models.BooleanField(default=False, verbose_name='Чувство стеснения в груди')),
                ('vomiting', models.BooleanField(default=False, verbose_name='Рвота')),
                ('dizziness', models.BooleanField(default=False, verbose_name='Головокружения')),
                ('headache', models.BooleanField(default=False, verbose_name='Головная боль')),
                ('blurred_consciousness', models.BooleanField(default=False, verbose_name='Помутнение сознания')),
                ('sweating', models.BooleanField(default=False, verbose_name='Потливость')),
                ('violation_of_balance_and_coordination', models.BooleanField(default=False, verbose_name='Нарушение равновесия и координации')),
                ('need_oxygen_support', models.BooleanField(default=False, verbose_name='Потребность в кислородной поддержке')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
    ]
