# Generated by Django 3.1.5 on 2021-08-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_patientexercises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientexercises',
            name='schedule',
        ),
        migrations.AddField(
            model_name='patientexercises',
            name='exercise',
            field=models.TextField(default='', verbose_name='Описание управжнения'),
        ),
    ]
